# Task ID: T319, T335, T336, T338
apiVersion: v1
kind: Service
metadata:
  name: mcp-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mcpServer.service.type }}
  ports:
  - port: {{ .Values.mcpServer.service.port }}
    targetPort: {{ .Values.mcpServer.service.port }}
  selector:
    app: mcp-server