apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ include "todo-app-v5.fullname" . }}-kubernetes-secret-store
  namespace: {{ .Values.namespace }}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []