apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app-v5.fullname" . }}-frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app-v5.labels" . | nindent 4 }}
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  type: {{ .Values.frontend.service.type }}